name: Deploy to Github Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Generate and Deploy Documentation ✍🏼
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create index
      run: cp README.md demo/index.md

    - name: Generate documentation files
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: demo/docfx.json

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        target_branch: gh-pages
        build_dir: demo/_site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
